spring:
  application:
    name: tutorapp-backend
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/tutorapp_dev
    username: tutorapp_dev
    password: dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:dev@tutorapp.com}
    password: ${EMAIL_PASSWORD:dev_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID_DEV}
            client-secret: ${GOOGLE_CLIENT_SECRET_DEV}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID_DEV}
            client-secret: ${FACEBOOK_CLIENT_SECRET_DEV}

app:
  jwt:
    secret: ${JWT_SECRET_DEV:devSecretKey123456789}
    expiration: 86400000 # 24h
    refresh-expiration: 604800000 # 7 jours

  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001

  file:
    upload-dir: ./uploads/dev
    max-size: 10485760

logging:
  level:
    com.backend.tutor_app: DEBUG
    org.springframework.security: DEBUG