spring:
  application:
    name: tutorapp-backend


  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tutorapp}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000 # 1h en prod
    refresh-expiration: 604800000 # 7 jours

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://tutorapp.com}

  file:
    upload-dir: ${FILE_UPLOAD_DIR:/var/tutorapp/uploads}
    max-size: 10485760

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

logging:
  level:
    com.backend.tutor_app: INFO
    org.springframework.security: WARN
  file:
    name: /var/log/tutorapp/application.log