package com.backend.tutor_app.dto.admin;

import com.backend.tutor_app.model.enums.ModerationStatus;
import com.backend.tutor_app.model.enums.ReportType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * DTO pour les signalements et modération
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserModerationDto {
    
    private Long id;
    
    // Informations du signalement
    private ReportType type;
    private ModerationStatus status;
    private String reason;
    private String description;
    private String evidence; // URL vers preuves (screenshots, etc.)
    
    // Utilisateur signalé
    private Long reportedUserId;
    private String reportedUserEmail;
    private String reportedUserName;
    private String reportedUserProfilePicture;
    
    // Utilisateur qui signale
    private Long reporterUserId;
    private String reporterEmail;
    private String reporterName;
    
    // Contenu signalé (si applicable)
    private String contentType; // "message", "profile", "review", etc.
    private Long contentId;
    private String contentPreview;
    private String contentUrl;
    
    // Traitement du signalement
    private LocalDateTime reportedAt;
    private LocalDateTime reviewedAt;
    private Long reviewedBy; // ID de l'admin
    private String reviewerName;
    private String actionTaken;
    private String moderatorComment;
    private String resolution;
    
    // Sévérité et priorité
    private String severity; // LOW, MEDIUM, HIGH, CRITICAL
    private String priority; // LOW, NORMAL, HIGH, URGENT
    private Boolean autoGenerated; // Si le signalement est automatique
    
    // Métadonnées
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private Integer reportCount; // Nombre de signalements similaires
}
